# https://docs.docker.com/compose/compose-file/compose-file-v3/#extension-fields
x-app: &app
  build: ./
  working_dir: /app
  volumes:
    - ./:/app
    - bundle:/usr/local/bundle
    - node_modules:/app/node_modules

services:
  app:
    << : *app
    command: ['bundle', 'exec', 'rails', 'server', '-p', '3003', '-b', '0.0.0.0']
    environment:
      RUBY_DEBUG_OPEN: 'true'
    ports:
      - 127.0.0.1:3003:3003
  js:
    << : *app
    build: ./
    command: ['esbuild', 'app/javascript/application.js', '--bundle', '--outdir=app/assets/builds', '--watch=forever']
  centrifugo:
    image: centrifugo/centrifugo:v5
    command: ['centrifugo', '--admin', '-c', 'config.json']
    ports:
      - 8000:8000
    volumes:
      - ./centrifugo:/centrifugo

volumes:
  bundle:
    driver: local
  node_modules:
    driver: local
