# https://docs.docker.com/compose/compose-file/compose-file-v3/#extension-fields
x-app: &app
  build:
    context: .
    target: dev
  working_dir: /app
  volumes:
    - ./:/app
    - bundle:/usr/local/bundle
    - node_modules:/app/node_modules

services:
  app:
    << : *app
    command: ['bundle', 'exec', 'rails', 'server', '-p', '3003', '-b', '0.0.0.0']
    environment:
      RUBY_DEBUG_OPEN: 'true'
      CENTRIFUGO_HOST: 'ws:centrifugo.lvh.me:8000'
    env_file:
      - development.env
    ports:
      # - 127.0.0.1:3003:3003
      - 0.0.0.0:3003:3003
    tmpfs:
      - /app/tmp/pids
    depends_on:
      - mongo
  js:
    << : *app
    command: ['esbuild', 'app/javascript/application.js', '--bundle', '--outdir=app/assets/builds', '--watch=forever', '--sourcemap']
  centrifugo:
    image: centrifugo/centrifugo:v5
    command: ['centrifugo', '--admin', '-c', 'config.json']
    ports:
      - 8000:8000
    volumes:
      - ./centrifugo:/centrifugo
  mongo:
    image: mongo:7.0
    volumes:
      - mongo:/data/db

volumes:
  bundle:
    driver: local
  node_modules:
    driver: local
  mongo:
    driver: local
