services:
  app:
    build: ./
    working_dir: /app
    command: ['bundle', 'exec', 'rails', 'server', '-p', '3003', '-b', '0.0.0.0']
    environment:
      RUBY_DEBUG_OPEN: 'true'
    ports:
      - 127.0.0.1:3003:3003
    volumes:
      - ./:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
  # js:
  #   command: ['npm', 'build', ''

volumes:
  bundle:
    driver: local
  node_modules:
    driver: local
