services:
  app:
    build: ./
    working_dir: /app
    command: ['bundle', 'exec', 'rails', 'server', '-p', '3003', '-b', '0.0.0.0']
    environment:
      RUBY_DEBUG_OPEN: 'true'
    ports:
      - 127.0.0.1:3003:3003
    volumes:
      - ./:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
  # js:
  #   command: ['npm', 'build', ''
  # centrifugo docker run --rm --ulimit nofile=262144:262144 -v $PWD:/centrifugo -p 8000:8000 centrifugo/centrifugo:v5 centrifugo -c config.json --admin
  centrifugo:
    image: centrifugo/centrifugo:v5
    command: ['centrifugo', '--admin', '-c', 'config.json']
    ports:
      - 8000:8000
    volumes:
      - ./centrifugo:/centrifugo

volumes:
  bundle:
    driver: local
  node_modules:
    driver: local
